web:
  password: ""
  port: 8899
  tls: false
  cert_path: ""
  key_path: ""
  public_url: ""
task:
  sync_interval: 60
  player_logging: true
  player_login_message: "玩家 {username} 加入服务器!\n当前在线人数: {online_num}"
  player_logout_message: "玩家 {username} 离开服务器!\n当前在线人数: {online_num}"
rcon:
  address: "127.0.0.1:25575"
  password: ""
  use_base64: true
  timeout: 5
rest:
  address: "http://127.0.0.1:8212"
  username: "admin"
  password: ""
  timeout: 5
save:
  path: "C:\\PalServer\\steamcmd\\steamapps\\common\\PalServer\\Pal\\Saved"
  decode_path: ""
  sync_interval: 40
  backup_interval: 14400
manage:
  kick_non_whitelist: false
